config/routes.rb
Rails.application.routes.draw do
  # get '/messages/new', to: 'messages#new'
  # post '/messages', to: 'messages#create'
  get 'pharmacies/index'

  get 'medications/index'
  devise_for :users
  root to: 'pages#home'

  resources :medication_orders, only: %i[new create show index]
  resources :donations, only: %i[new create index show]
  resources :pharmacies, only: :index
  resources :medications, only: :index

  get 'medications/reservation', to: 'medications#reservation'
  get 'pages/about', to: 'pages#about', as: "about"

  controller :pages do
    get :qr_code_generator
    get :qr_code_download
  end

end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer fixed-bottom">
  <div class="footer-links">
    <a href="https://github.com/andreiaptarifa/med4all"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-about-us">
  <%= link_to 'Sobre nós ', about_path %><i class="fas fa-heart"></i>
  </div>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn-unimportant" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <div class="d-flex align-items-center">
      <div class="px-1">
        <%= image_tag "https://res.cloudinary.com/dwzrjmdwm/image/upload/v1647812798/development/icons8-medicine-64_3_wisub3.png" %>
      </div>
      <div>
        <h1 class="mb-0 px-2">Remédio do bem<h1>
      </div>
    </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse bg-#0F4980" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Doar remédios", new_donation_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Reservar remédios", new_medication_order_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, width: 50, height: 45, crop: :thumb, gravity: :face, class: "photo dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "photo dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Perfil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Minhas Reservas", medication_orders_path, class: "dropdown-item" %>
              <%= link_to "Minhas doações", donations_path, class: "dropdown-item" %>
              <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Doar remédios", new_donation_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Reservar remédios", new_medication_order_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>