config/routes.rb
Rails.application.routes.draw do
  # get '/messages/new', to: 'messages#new'
  # post '/messages', to: 'messages#create'
  get 'pharmacies/index'

  get 'medications/index'
  devise_for :users
  root to: 'pages#home'

  resources :medication_orders, only: %i[new create show index]
  resources :donations, only: %i[new create index show]
  resources :pharmacies, only: :index
  resources :medications, only: :index

  get 'medications/reservation', to: 'medications#reservation'
  get 'pages/about', to: 'pages#about', as: "about"

  controller :pages do
    get :qr_code_generator
    get :qr_code_download
  end

end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user
  belongs_to :pharmacy
  belongs_to :medication
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donations, only: [:show]


  def new
    @donation = Donation.new
    @donation.user = current_user
    @address = "#{current_user.street} #{current_user.number}, #{current_user.city}"
    @pharmacies = Pharmacy.near(@address, 4)
    @markers = @pharmacies.map do |pharmacy|
      {
        lat: pharmacy.latitude,
        long: pharmacy.longitude,
        info_window: render_to_string(partial: "pharmacies/info_window", locals: { pharmacy: pharmacy }),
        image_url: helpers.asset_url("/assets/images/hospital-icon.png")
      }
    end
  end

  def create
    @donation = Donation.new(donations_params)
    @donation.user = current_user
    medication = Medication.find(params[:donation][:medication_id])
    @donation.medication = medication
    pharmacy = Pharmacy.find(params[:donation][:pharmacy_id])
    @donation.pharmacy = pharmacy
    if @donation.save
      if Inventory.find_by(medication: medication, pharmacy: pharmacy)
        inventory = Inventory.find_by(medication: medication, pharmacy: pharmacy)
        inventory.update!(units: inventory.units += @donation.units)
      else
        Inventory.create(units: @donation.units, medication: medication, pharmacy: pharmacy)
      end
      redirect_to donations_path, notice: "Sua doação foi criada e será encaminhada para #{@donation.pharmacy.pharmacy_name}. Obrigado, sua doação ajuda a salvar vidas!"
      # redirect_to root_path
    else
      render :new
    end
  end

  def index
    @donations = Donation.where(user_id: current_user.id)
  end

  def show
    @donation = Donation.find(params[:id])
  end

  private

  def donations_params
    params.require(:donation).permit(:units, :expiry_date, :pharmacy_id)
  end

  def set_donations
    @donation = Donation.find(params[:id])
  end
end

app/views/donations/_form.html.erb
<%= simple_form_for [donation] do |f|%>
  <%= f.input :units %>
  <%= f.input :expiry_date %>
  <%= f.association :medication, collection: Medication.all.order(:commercial_name), label_method: :name_and_concentration %>
  <%= f.association :pharmacy, collection: Pharmacy.all.order(:pharmacy_name), label_method: :pharmacy_name %>
  <%= f.button :submit, class: 'btn-medium' %>
<% end %>

app/views/donations/index.html.erb
<div class="new-container">
  <div class="table-new">
    <h2>Suas Doações</h2>
    <div class="table-content">
    <% @donations.each do |donation| %>
      <div class="table-grid">
        <span><strong><%= donation.medication.commercial_name %></strong></span>
        <span><%= donation.medication.active_substance %> - <%= donation.medication.concentration %></span>
        <span><%= donation.units %> comprimidos </span>
        <span class="text-center"><strong><%= donation.created_at.strftime('%d/%m/%y') %></strong></span>
      </div>
    <% end %>
    </div>
    <div class="d-flex justify-content-center border-top-0 align-items-center">
      <%= link_to "Faça Outra Doação", new_donation_path, class:"btn-green-secondary my-3" %>
    </div>
  </div>
</div>

app/views/donations/new.html.erb
<div class="new-container">

<div class="form-container" data-controller="display-results" data-display-results-position-value="beforeend">
  <h1 class="mb-5">Nova doação</h1>
    <div class="search-bar d-flex mt-4 mb-3">
      <div class="form-search col-10">
        <%= form_for :query, url: medications_path, method: :get, remote: true,
                                       data: {
                                          display_results_target: "form",
                                          action: "submit->display-results#search"
                                          } do |f| %>
          <div class="row d-flex justify-content-between">
          <div class="col-12 col-lg-7">
            <%= f.text_field :query,
              class: "form-control mx-2",
              placeholder: "Digite o nome do medicamento ou princípio ativo", data: { display_results_target: "input" }%>
          </div>
          <div class="search-btn col-12 col-lg-3">
            <%= f.submit "Procurar", class: "btn-donation mx-2"%>
          </div>
          </div>
      <% end %>
      </div>
  </div>

  <div data-controller="flatpickr">
  <%= simple_form_for [@donation] do |f|%>
      <div class="results-medications">
        <span data-display-results-target="results"></span>
      </div>
      <h5>
        <%= f.input :medication_id, :label => false , as: :hidden, input_html: { value: params[:medication_id] } %>
        <div class="row">
          <div class= "form-medication col-10 col-lg-5">
            <%= f.input :units, :label => "Nº de comprimidos", class:'d-none' %>
          </div>
           <div class= "form-medication col-10 col-lg-5">
            <%= f.input :expiry_date, label: "Data de validade", class: "d-none", as: :string, required: true, input_html: { class: "datepicker" } %>
          </div>
        </div>
          <div class="col-10">
            <%= f.association :pharmacy, :label => "Local de coleta", collection: @pharmacies.sort_by{ |p| p.pharmacy_name }, label_method: :pharmacy_name %>
            <%= f.button :submit, "Doar", class: 'btn-principal' %>
          </div>
      </h5>
  <% end %>
  </div>
  <h4>Unidades mais próximas a você: </h4>
  <% if @markers %>
  <div>
    <div style="width: 83%; height: 400px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      class="col-6">
    </div>
  </div>
<% end %>
</div>


</div>

app/views/donations/show.html.erb
<div class="d-flex justify-content-around donation-container container mb-3">
  <div class="row mt-5">
      <div class="donation">
      <h1>Você está doando o seguite medicamento:</h1>
        <table class="table table-striped">
        <tbody>
          <tr>
            <th scope="row">Medicamento</th>
            <td><%= @donation.medication.commercial_name.capitalize %></td>
          </tr>
          <tr>
            <th scope="row">Principio ativo</th>
            <td><%= @donation.medication.active_substance.capitalize %></td>
          </tr>
          <tr>
            <th scope="row">Concentração</th>
            <td><%= @donation.medication.concentration %></td>
          </tr>
          <tr>
            <th scope="row">Quantidade</th>
            <td><%= @donation.units %></td>
          </tr>
          <tr>
            <th scope="row">Data de validade</th>
            <td>De <%= @donation.expiry_date %></td>
          </tr>
          <tr>
            <th scope="row">Laboratório</th>
            <td>De <%= @donation.medication.lab.capitalize %></td>
          </tr>
        </tbody>
       </table>
       <h2>Sua doação é muito importante para nós!</h2>
     </div>
  </div>
</div>

<div class="d-flex justify-content-center container m-5">
  <%= link_to 'Suas doações', donations_path, class: 'btn-medium' %>
</div>