config/routes.rb
Rails.application.routes.draw do
  # get '/messages/new', to: 'messages#new'
  # post '/messages', to: 'messages#create'
  get 'pharmacies/index'

  get 'medications/index'
  devise_for :users
  root to: 'pages#home'

  resources :medication_orders, only: %i[new create show index]
  resources :donations, only: %i[new create index show]
  resources :pharmacies, only: :index
  resources :medications, only: :index

  get 'medications/reservation', to: 'medications#reservation'
  get 'pages/about', to: 'pages#about', as: "about"

  controller :pages do
    get :qr_code_generator
    get :qr_code_download
  end

end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord
  belongs_to :user
  belongs_to :medication
  belongs_to :pharmacy
end

app/controllers/medication_orders_controller.rb
class MedicationOrdersController < ApplicationController
  def index
    @medication_orders = MedicationOrder.where(user_id: current_user.id)
  end

  def new
    @medication_order = MedicationOrder.new
    if params[:medication_id] && params[:units]
      @inventories = Inventory.where(medication: Medication.find(params[:medication_id])).where('units >= ?', params[:units])
      @pharmacies = @inventories.map { |inventory| inventory.pharmacy }
      @markers = @pharmacies.map do |pharmacy|
        {
          lat: pharmacy.latitude,
          long: pharmacy.longitude,
          info_window: render_to_string(partial: "pharmacies/info_window", locals: { pharmacy: pharmacy }),
          image_url: helpers.asset_url("/assets/images/hospital-icon.png")
        }
      end
    end
  end

  def create
    @medication_order = MedicationOrder.new(medication_order_params)
    medication = Medication.find(params[:medication_order][:medication_id])
    units = params[:medication_order][:units]
    pharmacy = Pharmacy.find(params[:medication_order][:pharmacy_id])
    @medication_order.medication = medication
    @medication_order.user = current_user
    @medication_order.units = units
    @medication_order.pharmacy = pharmacy
    if @medication_order.save
      inventory = Inventory.find_by(medication: medication, pharmacy: pharmacy)
      inventory.units -= units.to_i
      inventory.save!
      account_sid = ENV['TWILIO_ACCOUNT_SID']
      auth_token = ENV['TWILIO_AUTH_TOKEN']
      @client = Twilio::REST::Client.new(account_sid, auth_token)
      @client.messages.create(
        from: '+18548423976',
        to: '+5517981537359',
        body: 'Você pode retirar seu remédio!'
      )
      redirect_to medication_order_path(@medication_order), notice: "Você recebeu um SMS de confirmação no número #{current_user.cellphone} e tem 24 horas para retirar seu remédio"
    else
      render :new
    end
  end

  def show
    @medication_order = MedicationOrder.find(params[:id])
    @qr_code = RQRCode::QRCode.new(@medication_order.qr_code)
    @svg = @qr_code.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      standalone: true,
      module_size: 3
    )
  end

  private
  def medication_order_params
    params.require(:medication_order).permit(:units, :medication_id, :pharmacy_id, :qr_code)
  end
end

app/views/medication_orders/index.html.erb
<div class="new-container">
  <div class="table-new">
    <h2> Suas Reservas </h2>
      <div class="table-content">
      <% @medication_orders.each do |medication_order| %>
        <div class="table-grid">
          <span><strong><%= medication_order.medication.active_substance %> - <%= medication_order.medication.concentration %></strong></span>
          <span><%= medication_order.units %> comprimidos</span>
          <span><%= medication_order.pharmacy.pharmacy_name %></span>
          <span class="text-center"><strong><%= medication_order.created_at.strftime('%d/%m/%y') %></strong></span>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/medication_orders/new.html.erb
<div class="new-container">
  <div>
    <div data-controller="display-orders" data-display-orders-position-value="beforeend">
      <div data-display-orders-target ="search">
        <h1>Reserve um medicamento:</h1>
        <div class="search-bar mt-4 mb-3 justify-content-between">
          <div class="form-search">
            <%= form_for :query, url: medications_reservation_path, method: :get, remote: true,
                                          data: {
                                            display_orders_target: "form",
                                            action: "submit->display-orders#search"
                                            } do |f| %>
              <div class="row justify-content-between">
              <div class="col-12 col-lg-7">
                <%= f.text_field :query,
                  class: "form-control form-height",
                  placeholder: "Digite o nome do medicamento ou princípio ativo",
                  data: { display_orders_target: "input" }%>
              </div>
              <div class="col-12 col-lg-3">
                <%= f.text_field :units,
                    class: "form-control form-height",
                    placeholder: "N° de comprimidos",
                    data: { display_orders_target: "units" }%>
              </div>
                <div class="search-button col-12 col-lg-2">
                  <%= f.submit "Procurar", class: "btn-search-medication" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    <div id="anchor-text">
    </div>
      <div>
        <span data-display-orders-target="results" class="d-none"><strong>Selecione seu medicamento:</strong></span>
        <% if params[:medication_id] %>
          <% if @pharmacies.count.positive? %>
              <%= simple_form_for @medication_order, html: { data: { display_orders_target: "medications", insert_in_list_target:"pharmacy"} }, class:"d-none" do |f| %>
                <%= f.input :medication_id, label: false, class: "form-control form-control-lg", as: :hidden, input_html: { value: params[:medication_id] } %>
                <%= f.input :units, label: false, class: "form-control form-control-lg", as: :hidden, input_html: { value: params[:units] } %>
                <%= f.input :qr_code, as: :hidden, input_html: { value: "Reserva para: #{current_user.first_name.capitalize} #{current_user.last_name.capitalize} - Nº da Reserva: #{rand(1000..3000)}" } %>
                <%= f.association :pharmacy, :label => "Local de coleta", collection: @pharmacies, label_method: :pharmacy_name %>
                <%= f.submit "Reservar", class: 'btn-principal' %>
              <% end %>
            <% else %>
              <p>Não temos esse medicamento</p>
            <% end %>
          <% end %>
        </div>

    </div>
    <% if @markers && @markers.count.positive? %>
      <h5 class="mt-5">Unidades com o medicamento disponível: </h5>
      <div class="d-flex justify-content">
        <div style="width: 100%; height: 400px;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/medication_orders/show.html.erb
<section class="page-contain new-container">
  <div class="data-card">
    <h3><%= link_to "#{@medication_order.medication.commercial_name}", medication_orders_path, class:"title" %></h3>
    <h4><%= @medication_order.units %> comprimidos reservados<h4>
    <h5>Você tem 24 horas para retirar seu medicamento no posto <%= @medication_order.pharmacy.pharmacy_name %></h5>
    <span class="link-text">
    <div class='d-flex align-items-end qr-code'>
      <div class="px-3">
      <%= @svg.html_safe %>
      </div>
      <p>Apresente o QR Code para retirar sua reserva</p>
      <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
        <%# <path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#EE6780"/> %>
      </svg>
    </div>
    </span>
  </div>
</section>